# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pr: 
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageClassFilesDirectories: 'build/classes/main/'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Books API SonarCloud'
    organization: 'project-books-1'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=project-books_Books-API
      sonar.projectName=Books API
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Test run'
    buildPlatform: 'JUnit'

- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload to codecov.io'
